services:
  airwars-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-instancing-service:latest
    container_name: aw-sis
    ports:
      - "127.0.0.1:5000:8080"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - GameServer__LauncherType=Docker
      - GameServer__IpAddress=airwars.online
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
